# Generated by Django 5.1.1 on 2024-09-20 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_restaurant_alter_table_options_table_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='reservations.restaurant'),
            preserve_default=False,
        ),
    ]
