# Generated by Django 5.1.1 on 2024-09-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_table_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MergedTable',
        ),
        migrations.AlterUniqueTogether(
            name='openingschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(default='unkown@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='name',
            field=models.CharField(default='Guest', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='phone',
            field=models.CharField(default='+6512345678', max_length=15),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='table',
            name='merged_with',
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name='table',
            name='merged_with',
            field=models.ManyToManyField(blank=True, to='reservations.table'),
        ),
    ]
