# Generated by Django 5.1.1 on 2024-09-23 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_administrator_delete_mergedtable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openingschedule',
            name='sessions',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('opening_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reservations.openingschedule')),
            ],
        ),
    ]
