# Generated by Django 5.1.1 on 2024-09-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_openingschedule_sessions_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='openingschedule',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
