# Generated by Django 5.1.1 on 2024-09-23 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_openingschedule_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='opening_schedule',
        ),
        migrations.AddField(
            model_name='openingschedule',
            name='sessions',
            field=models.ManyToManyField(blank=True, to='reservations.session'),
        ),
        migrations.AddField(
            model_name='session',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='reservations.restaurant'),
            preserve_default=False,
        ),
    ]
