# Generated by Django 5.1.1 on 2024-09-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_session_opening_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(editable=False),
        ),
    ]
