# Generated by Django 5.1.1 on 2024-09-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservation_end_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='capacity',
            new_name='default_capacity',
        ),
        migrations.AddField(
            model_name='table',
            name='max_capacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='table',
            name='merged_capacity',
            field=models.IntegerField(default=4),
        ),
    ]
